name: flutter_danain
description: Simple auth app flutter, server node.js, BLoC pattern, RxDart.

publish_to: 'none'
version: 1.6.57
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=3.3.3'

dependencies:
  android_intent: ^2.0.2
  bloc: ^8.1.2
  bottom_picker: ^2.6.0
  built_value: ^8.4.2
  camera: ^0.10.5+4
  cancellation_token_hoc081098: ^1.0.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.13.3
  connectivity: ^3.0.6
  connectivity_plus: ^5.0.2
  crypto: ^3.0.3
  cupertino_http: ^1.0.1
  cupertino_icons: ^1.0.5
  dart_either: ^1.0.0
  dart_jsonwebtoken: ^2.11.0
  dartz: ^0.10.1
  device_info_plus: ^9.1.1
  did_change_dependencies: ^1.0.0
  disposebag: ^1.5.1
  dotted_border: ^2.0.0+3
  equatable: ^2.0.5
  ffi: ^2.0.1
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.4.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_database: ^10.3.8
  firebase_messaging: ^14.7.9
  firebase_performance: ^0.9.3+8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_bloc_pattern: ^2.3.0
  flutter_cached_pdfview: ^0.4.2
  flutter_custom_month_picker: ^0.1.3
  flutter_disposebag: ^1.1.0
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^5.0.11
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  flutter_otp_text_field: ^1.1.1
  flutter_pdfview: ^1.3.1
  flutter_provider: ^2.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  google_fonts: ^4.0.4
  hexcolor: ^3.0.1
  http: ^0.13.5
  http_client_hoc081098: ^0.0.1-dev.0
  intl: ^0.18.1
  js: ^0.6.7
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  localstorage: ^4.0.1+4
  location: ^5.0.3
  logger: ^2.2.0
  meta: ^1.5.1
  oktoast: ^3.4.0
  onesignal_flutter: ^5.0.4
  package_info_plus: ^5.0.1
  path: ^1.8.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.0.0
  pinput: ^3.0.1
  platform_device_id: ^1.0.1
  provider: ^6.0.5
  qr_flutter: ^4.0.0
  rx_shared_preferences: ^3.1.0
  rxdart: ^0.27.7
  rxdart_ext: ^0.2.7
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  showcaseview: ^2.1.0
  sleek_circular_slider: ^2.0.1
  step_progress_indicator: ^1.0.2
  tuple: ^2.0.1
  uni_links: ^0.5.1
  url_launcher: ^6.1.11
  webview_flutter: ^4.4.1

dev_dependencies:
  analyzer: ^6.2.0
  build_runner: ^2.3.2
  built_value_generator: ^8.4.2
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter_icons:
  color: '#ffffff'
  image_path: 'assets/images/logo/logo_splash.png'
  fullscreen: true
  android: true
  ios: true
  web: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/logo/splash.png'
  android_disable_fullscreen: true
  android_gravity: center
  android: true
  ios: true
  web: true
  android12: true
  android_12:
    color: '#ffffff'
    image: 'assets/images/logo/splash.png'

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.development
    - .env.production
    - .env.staging
    - assets/files/syarat_ketentuan.pdf
    - assets/files/kebijakan_privasi.pdf
    - assets/bg.jpg
    - assets/images/Danain.svg
    - assets/images/logo/afpi.svg
    - assets/images/logo/logo_ojk.svg
    - assets/images/logo/Danain1.svg
    - assets/images/logo/danain2.svg
    - assets/images/logo/logo_splash.png
    - assets/images/logo/danain.png
    - assets/images/onboarding/lender.svg
    - assets/images/onboarding/lender.png
    - assets/images/onboarding/peminjam.svg
    - assets/images/onboarding/peminjam.png
    - assets/images/onboarding/pinjaman_beragunan_emas.svg
    - assets/images/onboarding/cicilan_emas.svg
    - assets/images/preference/cicil_emas.svg
    - assets/images/preference/product.svg
    - assets/images/preference/gadai_emas.svg
    - assets/images/preference/produk_cicil_emas.svg
    - assets/images/preference/produk_gadai_emas.svg
    - assets/images/preference/kunci_harga_emas.svg
    - assets/images/preference/uang_muka_terjangkau.svg
    - assets/images/preference/pilihan_tenor_bervariasi.svg
    - assets/images/preference/simulasi_cicilan.svg
    - assets/images/preference/jangkauan_supplier_emas.svg
    - assets/images/preference/question.svg
    - assets/images/preference/maxi_150.svg
    - assets/images/preference/bubble.svg
    - assets/images/preference/simulasi_pinjaman.svg
    - assets/images/preference/lokasi_penyimpan_emas.svg
    - assets/images/register/aktifkan_lokasi.svg
    - assets/images/register/warning.svg
    - assets/images/register/change_email.svg
    - assets/images/register/expired.svg
    - assets/images/forgot_password/forgot_password.svg
    - assets/images/forgot_password/send_email.svg
    - assets/images/forgot_password/success_change_password.svg
    - assets/images/simulasi/antam.svg
    - assets/images/simulasi/ubs.svg
    - assets/images/simulasi/galeri.png
    - assets/images/simulasi/lotus.svg
    - assets/images/simulasi/simulasi.svg
    - assets/images/logo/splash.png
    - assets/images/icons/dropdown.svg
    - assets/images/home/simulasi_cicilan2.svg
    - assets/images/home/background_borrower.svg
    - assets/images/home/pinjaman.svg
    - assets/images/home/mitra.svg
    - assets/images/home/maxi.svg
    - assets/images/home/maxi_2.svg
    - assets/images/home/maxi_3.svg
    - assets/images/home/nyicil_emas.svg
    - assets/images/home/datadiri.svg
    - assets/images/home/datadirilender.svg
    - assets/images/home/pinjaman_dana.svg
    - assets/images/home/datadiri-verif.svg
    - assets/images/home/aktifasi_akun.svg
    - assets/images/home/header_home.svg
    - assets/images/home/peminjam_bpkb.png
    - assets/images/home/header_profile.svg
    - assets/images/home/profile_user_icon.svg
    - assets/images/home/datadiri-progress.svg
    - assets/images/home/verification.svg
    - assets/images/home/background.svg

    - assets/images/home/tkb_0.png
    - assets/images/home/tkb_30.png
    - assets/images/home/tkb_60.png
    - assets/images/home/tkb_90.png

    #icons
    - assets/images/icons/dropdown.svg
    - assets/images/icons/car.svg
    - assets/images/icons/motor.svg
    - assets/images/icons/home.svg
    - assets/images/icons/data_pribadi_lender.svg
    - assets/images/icons/history.svg
    - assets/images/icons/help.svg
    - assets/images/icons/profile.svg
    - assets/images/icons/check.svg
    - assets/images/icons/loading_danain.png
    - assets/images/icons/payung.svg
    - assets/images/icons/kupon.svg
    - assets/images/icons/portfolio.svg
    - assets/images/icons/process.svg
    - assets/images/icons/shield.svg
    - assets/images/icons/warning_red.svg
    - assets/images/icons/update.svg
    - assets/images/icons/product.svg
    - assets/images/icons/faq/icon_1.svg
    - assets/images/icons/faq/icon_2.svg
    - assets/images/icons/faq/icon_3.svg
    - assets/images/icons/faq/icon_4.svg
    - assets/images/icons/faq/icon_5.svg
    - assets/images/icons/faq/icon_6.svg
    - assets/images/icons/faq/icon_7.svg
    - assets/images/icons/faq/mail.svg
    - assets/images/icons/faq/phone.svg
    - assets/images/icons/faq/whatsapp.svg
    - assets/images/icons/rotate.svg
    - assets/images/icons/notif.svg
    - assets/images/transaction/no_transaction.svg
    - assets/images/transaction/detail_pinjaman.png
    - assets/images/icons/error_icon.svg
    - assets/images/icons/mitra.svg
    - assets/images/icons/edit_icon.svg
    - assets/images/icons/edit_icon_lender.svg
    - assets/images/icons/empty_search.svg
    - assets/images/icons/search.svg
    - assets/images/icons/close_circle.svg
    - assets/images/panduan/selfiektp.svg
    - assets/images/panduan/kk.svg
    - assets/images/icons/icCar.svg
    - assets/images/panduan/sim.svg
    - assets/images/transaction/toko_emas.png
    - assets/images/transaction/gagal_cicil.svg
    - assets/images/transaction/background_transaksi.svg
    - assets/images/transaction/background_transaksi_3.svg
    - assets/images/transaction/proses_pengajuan.svg
    - assets/images/transaction/detail_pinjaman2.svg
    - assets/images/logo/bank/bni.svg
    - assets/images/icons/back.svg
    - assets/images/icons/location_failed.svg
    - assets/images/icons/no_message.svg
    - assets/images/icons/profile/person.svg
    - assets/images/icons/profile/credit_card.svg
    - assets/images/icons/profile/logout.svg
    - assets/images/icons/profile/privasi.svg
    - assets/images/icons/profile/settings.svg
    - assets/images/icons/profile/syarat.svg
    - assets/images/icons/profile/email.svg
    - assets/images/icons/profile/password.svg
    - assets/images/icons/profile/close_acc.svg
    - assets/images/icons/profile/close_acc_borrower.svg
    - assets/images/icons/profile/data_ktp.svg
    - assets/images/icons/profile/data_aktivasi.svg
    - assets/images/icons/icCall.svg
    - assets/images/icons/square_icCar.svg
    - assets/images/icons/square_icMotor.svg
    - assets/images/icons/icMitra_borrower.svg
    - assets/images/icons/icSurveyor_borrower.svg
    - assets/images/icons/icSurveyor_borrower.png

    #verification
    - assets/images/verification/example_ktp.svg
    - assets/images/verification/fill_personal_data.svg
    - assets/images/verification/take_swafoto.svg
    - assets/images/verification/verification.svg
    - assets/images/verification/verif.svg
    - assets/images/verification/unverif.svg
    - assets/images/verification/not_verif.svg
    - assets/images/verification/verif_logo.svg

    #others
    - assets/images/others/bni_logo.svg
    - assets/images/others/penangguhan.svg
    - assets/images/others/penangguhan_lender.svg

    #transaction
    - assets/images/transaction/no_transaction.svg
    - assets/images/transaction/detail_pinjaman.png
    - assets/images/transaction/toko_emas.png
    - assets/images/transaction/gagal_cicil.svg
    - assets/images/transaction/background_transaksi.svg
    - assets/images/transaction/default_background.png
    - assets/images/transaction/ilustration_checkin.svg
    - assets/images/transaction/icon_barcode.svg
    - assets/images/transaction/image_people_default.png
    - assets/images/transaction/background_cashback_pinjam.svg
    - assets/images/transaction/ic_cashback.svg

    #panduan
    - assets/images/panduan/selfiektp.svg
    - assets/images/panduan/kk.svg
    - assets/images/panduan/sim.svg

    #profile
    - assets/images/profile/bank_template.svg
    - assets/images/profile/sim_card.svg
    - assets/images/profile/master_card.svg
    - assets/images/profile/bank.svg
    - assets/images/profile/check_shield.svg

    #lender
    - assets/images/forgot_password/send_gmail_lender.svg
    - assets/lender/onboarding/slider_1.svg
    - assets/lender/onboarding/slider_2.svg
    - assets/lender/onboarding/slider_3.svg
    - assets/lender/onboarding/Email.svg
    - assets/lender/onboarding/gmail_success.svg
    - assets/lender/register/make_pin.svg
    - assets/lender/register/shield_pin.svg
    - assets/lender/home/background.svg
    - assets/lender/home/bg_top.svg
    - assets/lender/home/setordana.svg
    - assets/lender/home/tarikdana.svg
    - assets/lender/home/verification.svg
    - assets/lender/home/bank.svg
    - assets/lender/home/development.svg
    - assets/lender/home/simulasi.svg
    - assets/lender/home/payung2.svg
    - assets/lender/home/hadiah.svg
    - assets/lender/bank/bca.svg
    - assets/lender/bank/bni.svg
    - assets/lender/bank/atm_bersama.svg
    - assets/lender/pendanaan/produk.svg
    - assets/lender/pendanaan/waiting.svg
    - assets/lender/pendanaan/bubble_merah.svg
    - assets/lender/pendanaan/cicil_emas.svg
    - assets/lender/pendanaan/maxi.svg
    - assets/lender/pendanaan/arrow.svg
    - assets/lender/pendanaan/saldo_not_enough.svg
    - assets/lender/pendanaan/pendanaan_default.png
    - assets/lender/pendanaan/cicil_emas_default.png
    - assets/lender/pendanaan/maxi_default.png
    - assets/lender/pendanaan/empty.svg
    - assets/images/home/background_home_lender.svg
    - assets/lender/portofolio/background.svg
    - assets/lender/portofolio/dokumen.svg
    - assets/lender/portofolio/calculator.svg
    - assets/lender/portofolio/terlambat.svg
    - assets/lender/portofolio/terlambat_cicil_emas.svg
    - assets/lender/portofolio/pembatalan.svg
    - assets/lender/portofolio/pembatalan_cicil_emas.svg
    - assets/lender/portofolio/bg-riwayat-transaksi.svg
    - assets/lender/portofolio/alert.svg
    - assets/lender/portofolio/foto1.svg
    - assets/lender/portofolio/dompet.svg
    - assets/lender/portofolio/filter.svg
    - assets/lender/portofolio/Like.svg
    - assets/lender/portofolio/arrow_top_right.svg
    - assets/lender/portofolio/alert_fill.svg
    - assets/lender/portofolio/Car_1.png
    - assets/lender/portofolio/Motorcycle.png
    - assets/lender/portofolio/chev_right.svg
    - assets/lender/profile/add_user.svg
    - assets/lender/profile/ajak_teman.svg
    - assets/lender/profile/whatsapp.svg
    - assets/lender/profile/x.svg
    - assets/lender/profile/link.svg
    - assets/lender/profile/telegram.svg
    - assets/lender/profile/icon_user.svg
    - assets/lender/profile/icon_user_borrower.svg
    - assets/lender/pendanaan/dompet.svg
    - assets/lender/pendanaan/alert.svg
    - assets/lender/pendanaan/filter.svg
    - assets/lender/pendanaan/maxi_logo.svg
    - assets/lender/pendanaan/check.svg
    - assets/lender/pendanaan/cicil_emas_logo.svg
    - assets/lender/pendanaan/cicil_emas_2.png
    - assets/lender/tarikDana/tarik_dana_proses.svg
    - assets/lender/verifikasi/data_diri.svg
    - assets/lender/verifikasi/confirmation.svg
    - assets/lender/verifikasi/scan_data.svg
    - assets/lender/profile/shield.svg
    - assets/lender/profile/complete_bank.svg
    - assets/lender/loading/danain.png
    - assets/lender/pendanaan/pending.svg
    - assets/lender/pendanaan/Datadiri.svg
    - assets/lender/pendanaan/warning.svg
    - assets/lender/pendanaan/setordana.svg
    - assets/borrower/transaksi/chevron-right.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf
